/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseInput: typeof import('./src/components/ui/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/ui/BaseModal.vue')['default']
    BaseRange: typeof import('./src/components/ui/BaseRange.vue')['default']
    BaseSelect: typeof import('./src/components/ui/BaseSelect.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
